services:
    runner:
        container_name: maskbench_dev_${USER}
        build: .                
        env_file: 
          - .env
        volumes:
          - ./src:/src          
          - ./poetry.lock:/poetry.lock 
          - ./pyproject.toml:/pyproject.toml
          - ./config:/config
          - ${MASKBENCH_DATASET_DIR}:/datasets  
          - ${MASKBENCH_OUTPUT_DIR}:/output
        tty: true              # Keep the container running interactively
        stdin_open: true