models:
  - name: MediaPipePose
    enabled: true
    module: models.mediapipe_pose_estimator
    class: MediaPipePoseEstimator
    config:
      weights: pose_landmarker_lite.task

  - name: YoloPose
    enabled: true
    module: models.yolo_pose_estimator
    class: YoloPoseEstimator
    config:
      weights: yolo11n-pose.pt
      confidence_threshold: 0.85

  - name: OpenPose
    enabled: true
    module: models.open_pose_estimator
    class: OpenPoseEstimator      

dataloader:
  name: TedTalks
  module: dataloader.TED_dataloader
  class: TedDataloader
  dataset_folder: /datasets/ted-talks
  batch_size: 1
  shuffle: false
