pose_estimators:
  - name: MediaPipePose
    enabled: false
    module: models.mediapipe_pose_estimator
    class: MediaPipePoseEstimator
    config:
      weights: pose_landmarker_lite.task

  - name: YoloPose
    enabled: false
    module: models.yolo_pose_estimator
    class: YoloPoseEstimator
    config:
      weights: yolo11n-pose.pt
      confidence_threshold: 0.85

  - name: MaskAnyoneUi
    enabled: false
    module: models.maskanyone_ui_pose_estimator
    class: MaskAnyoneUiPoseEstimator  
    config:
      dataset_folder_path: /maskanyone_ui/dataset    

  - name: OpenPose
    enabled: false
    module: models.open_pose_estimator
    class: OpenPoseEstimator      

dataset:
  name: TragicTalkers
  module: datasets.tragic_talkers_dataset
  class: TragicTalkersDataset
  dataset_folder: /datasets/tragic_talkers

# dataset:
#   name: TedTalks
#   module: datasets.ted_dataset
#   class: TedDataset
#   dataset_folder: /datasets/ted-talks
