pose_estimators:
  - name: MediaPipePose
    enabled: true
    module: models.mediapipe_pose_estimator
    class: MediaPipePoseEstimator
    config:
      weights: pose_landmarker_lite.task

  - name: YoloPose
    enabled: true
    module: models.yolo_pose_estimator
    class: YoloPoseEstimator
    config:
      weights: yolo11n-pose.pt
      confidence_threshold: 0.85
  
  - name: MaskAnyone_Api
    enabled: true
    module: models.maskanyone_api_pose_estimator
    class: MaskAnyoneApiPoseEstimator
    config:
      hiding_strategy: pixelation
      overlay_strategy: mp_pose
      
  - name: MaskAnyoneUi
    enabled: true
    module: models.maskanyone_ui_pose_estimator
    class: MaskAnyoneUiPoseEstimator  
    config:
      dataset_folder_path: /maskanyone_ui/dataset    

  - name: OpenPose
    enabled: true
    module: models.open_pose_estimator
    class: OpenPoseEstimator      

dataset:
  name: TragicTalkers
  module: datasets.tragic_talkers_dataset
  class: TragicTalkersDataset
  dataset_folder: /datasets/tragic_talkers
  config:
    video_folder: videos
    ground_truth_folder: labels/pose_keypoints
    combine_ground_truth_files: true

# dataset:
#   name: TedTalks
#   module: datasets.ted_dataset
#   class: TedDataset
#   dataset_folder: /datasets/ted-talks
  
metrics:
  - name: AccelerationMetric
    module: evaluation.metrics.acceleration
    class: AccelerationMetric
