video_input_folder: /ted-talks
models:
  - name: MediaPipePose
    enabled: true
    module: models.mediapipe_pose_estimator
    class: MediaPipePoseEstimator
    config:
      weights: "mediapipe_pose.task"

  - name: YoloPose
    enabled: true
    module: models.yolo_pose_estimator
    class: YoloPoseEstimator
    config:
      weights: "yolo11n-pose.pt"
      confidence_threshold: 0.85

renderers:
  - name : PoseRender
    module: render.pose_render 
    class: PoseRender
