video_input_folder: /ted-talks
models:
  - name: YoloPose
    enabled: true
    module: models.yolo_pose_estimator
    class: YoloPoseEstimator
    config:
      weights: "yolo11n-pose.pt"
      confidence_threshold: 0.85
