video_input_folder: /ted-talks
models:
  - name: MediaPipePose
    enabled: false
    module: models.mediapipe_pose_estimator
    class: MediaPipePoseEstimator
    config:
      weights: pose_landmarker_lite.task

  - name: YoloPose
    enabled: false
    module: models.yolo_pose_estimator
    class: YoloPoseEstimator
    config:
      weights: yolo11n-pose.pt
      confidence_threshold: 0.85
  
  - name: MaskAnyone
    enabled: true
    module: models.maskanyone_pose_estimator
    class: MaskAnyonePoseEstimator
    config:
      hiding_strategy: pixelation
      overlay_strategy: mp_pose
      

dataloader:
  name: TedTalks
  module: dataloader.TED_dataloader
  class: TedDataloader
  dataset_folder: /datasets/ted-talks
  batch_size: 1
  shuffle: false
