checkpoint_name: None # comment out or set to "None"to run inference from scratch

dataset:
  name: TedTalks
  module: datasets.ted_dataset
  class: TedDataset
  dataset_folder: /datasets/ted-talks

# dataset:
#   name: TragicTalkers
#   module: datasets.tragic_talkers_dataset
#   class: TragicTalkersDataset
#   dataset_folder: /datasets/tragic_talkers
#   config:
#     video_folder: videos
#     ground_truth_folder: labels
#     convert_gt_keypoints_to_coco: true

pose_estimators:
  - name: MediaPipePose
    enabled: true
    module: models.mediapipe_pose_estimator
    class: MediaPipePoseEstimator
    config:
      weights: pose_landmarker_heavy.task
      max_num_poses: 3
      save_keypoints_in_coco_format: true
      confidence_threshold: 0.4

  - name: YoloPose
    enabled: true
    module: models.yolo_pose_estimator
    class: YoloPoseEstimator
    config:
      weights: yolo11n-pose.pt
      save_keypoints_in_coco_format: true
      confidence_threshold: 0.6

  - name: OpenPose
    enabled: true
    module: models.open_pose_estimator
    class: OpenPoseEstimator
    config:
      save_keypoints_in_coco_format: true
      confidence_threshold: 0.15
  
  - name: MaskAnyoneApi
    enabled: true
    module: models.maskanyone_api_pose_estimator
    class: MaskAnyoneApiPoseEstimator
    config:
      hiding_strategy: pixelation
      overlay_strategy: mp_pose
      save_keypoints_in_coco_format: true
      confidence_threshold: 0
      
  - name: MaskAnyoneUi
    enabled: true
    module: models.maskanyone_ui_pose_estimator
    class: MaskAnyoneUiPoseEstimator  
    config:
      dataset_folder_path: /datasets/maskanyone_ui    
      overlay_strategy: mp_pose
      hiding_strategy: pixelation
      save_keypoints_in_coco_format: true
      confidence_threshold: 0

metrics:
  - name: AccelerationMetric
    module: evaluation.metrics.acceleration
    class: AccelerationMetric
