pose_estimators:
  - name: MediaPipePose
    enabled: false
    module: models.mediapipe_pose_estimator
    class: MediaPipePoseEstimator
    config:
      weights: pose_landmarker_lite.task

  - name: YoloPose
    enabled: false
    module: models.yolo_pose_estimator
    class: YoloPoseEstimator
    config:
      weights: yolo11n-pose.pt
      confidence_threshold: 0.85
  
  - name: MaskAnyone_Api
    enabled: true
    module: models.maskanyone_api_pose_estimator
    class: MaskAnyoneApiPoseEstimator
    config:
      hiding_strategy: pixelation
      overlay_strategy: mp_pose
      
  - name: OpenPose
    enabled: false
    module: models.open_pose_estimator
    class: OpenPoseEstimator      

dataset:
  name: TedTalks
  module: datasets.ted_dataset
  class: TedDataset
  dataset_folder: /datasets/ted-talks
