checkpoint_name: None # comment out or set to "None" to run inference from scratch

dataset:
  name: RawMaskedExperiment
  module: datasets.ted_dataset
  class: TedDataset
  dataset_folder: /datasets/raw-masked-experiment/videos/raw
  # dataset_folder: /datasets/raw-masked-experiment/videos/blurring
  # dataset_folder: /datasets/raw-masked-experiment/videos/pixelation
  # dataset_folder: /datasets/raw-masked-experiment/videos/contours
  # dataset_folder: /datasets/raw-masked-experiment/videos/inpainting


pose_estimators:
  - name: YoloPose
    enabled: true
    module: models.yolo_pose_estimator
    class: YoloPoseEstimator
    config:
      weights: yolo11l-pose.pt
      save_keypoints_in_coco_format: true
      confidence_threshold: 0.4

  - name: MediaPipePose
    enabled: true
    module: models.mediapipe_pose_estimator
    class: MediaPipePoseEstimator
    config:
      weights: pose_landmarker_heavy.task
      max_num_poses: 3
      save_keypoints_in_coco_format: true
      confidence_threshold: 0.4

  - name: OpenPose
    enabled: true
    module: models.open_pose_estimator
    class: OpenPoseEstimator
    config:
      save_keypoints_in_coco_format: true
      overlay_strategy: BODY_25B
      confidence_threshold: 0.15
  
  - name: MaskAnyoneAPI-MediaPipe
    enabled: true
    module: models.maskanyone_api_pose_estimator
    class: MaskAnyoneApiPoseEstimator
    config:
      overlay_strategy: mp_pose
      save_keypoints_in_coco_format: true
      confidence_threshold: 0

  - name: MaskAnyoneAPI-OpenPose
    enabled: true
    module: models.maskanyone_api_pose_estimator
    class: MaskAnyoneApiPoseEstimator
    config:
      overlay_strategy: openpose_body25b
      save_keypoints_in_coco_format: true
      confidence_threshold: 0

  - name: MaskAnyoneUI-MediaPipe
    enabled: true
    module: models.maskanyone_ui_pose_estimator
    class: MaskAnyoneUiPoseEstimator  
    config:
      dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_mediapipe/raw
      # dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_mediapipe/blurring
      # dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_mediapipe/pixelation
      # dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_mediapipe/contours
      # dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_mediapipe/inpainting
      overlay_strategy: mp_pose
      save_keypoints_in_coco_format: true
      confidence_threshold: 0

  - name: MaskAnyoneUI-OpenPose
    enabled: true
    module: models.maskanyone_ui_pose_estimator
    class: MaskAnyoneUiPoseEstimator  
    config:
      dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_openpose/raw
      # dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_openpose/blurring
      # dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_openpose/pixelation
      # dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_openpose/contours
      # dataset_folder_path: /datasets/raw-masked-experiment/maskanyone_ui_openpose/inpainting
      overlay_strategy: openpose_body25b
      save_keypoints_in_coco_format: true
      confidence_threshold: 0
  
metrics:
  - name: AccelerationMetric
    module: evaluation.metrics.acceleration
    class: AccelerationMetric
