inference_checkpoint_name: None # comment out or set to "None" to run inference from scratch
execute_evaluation: true        # set to false to skip calculating evaluation metrics and plotting
execute_rendering: true         # set to false to skip rendering the videos

dataset:
  name: TED-kid
  code_file: datasets.ted_dataset.TedDataset
  dataset_folder: /datasets/TED-kid/videos

pose_estimators:
  - name: YoloPose
    enabled: true
    code_file: models.yolo_pose_estimator.YoloPoseEstimator
    config:
      weights: yolo11l-pose.pt
      save_keypoints_in_coco_format: true
      confidence_threshold: 0.4

  - name: MediaPipePose
    enabled: true
    code_file: models.mediapipe_pose_estimator.MediaPipePoseEstimator
    config:
      weights: pose_landmarker_heavy.task
      max_num_poses: 3
      save_keypoints_in_coco_format: true
      confidence_threshold: 0.4

  - name: OpenPose
    enabled: true
    code_file: models.open_pose_estimator.OpenPoseEstimator
    config:
      save_keypoints_in_coco_format: true
      overlay_strategy: BODY_25B
      confidence_threshold: 0.15
  
  - name: MaskAnyoneAPI-MediaPipe
    enabled: true
    code_file: models.maskanyone_api_pose_estimator.MaskAnyoneApiPoseEstimator
    config:
      overlay_strategy: mp_pose
      save_keypoints_in_coco_format: true
      confidence_threshold: 0

  - name: MaskAnyoneAPI-OpenPose
    enabled: true
    code_file: models.maskanyone_api_pose_estimator.MaskAnyoneApiPoseEstimator
    config:
      overlay_strategy: openpose_body25b
      save_keypoints_in_coco_format: true
      confidence_threshold: 0

  - name: MaskAnyoneUI-MediaPipe
    enabled: true
    code_file: models.maskanyone_ui_pose_estimator.MaskAnyoneUiPoseEstimator  
    config:
      dataset_folder_path: /datasets/TED-kid/maskanyone_ui_mediapipe/raw
      overlay_strategy: mp_pose
      save_keypoints_in_coco_format: true
      confidence_threshold: 0

  - name: MaskAnyoneUI-OpenPose
    enabled: true
    code_file: models.maskanyone_ui_pose_estimator.MaskAnyoneUiPoseEstimator  
    config:
      dataset_folder_path: /datasets/TED-kid/maskanyone_ui_openpose/raw
      overlay_strategy: openpose_body25b
      save_keypoints_in_coco_format: true
      confidence_threshold: 0
  
metrics:
  - name: Velocity
    code_file: evaluation.metrics.velocity.VelocityMetric
    config:
      time_unit: frame

  - name: Acceleration
    code_file: evaluation.metrics.acceleration.AccelerationMetric
    config:
      time_unit: frame
  
  - name: Jerk
    code_file: evaluation.metrics.jerk.JerkMetric
    config:
      time_unit: frame

